hadd -k -f VBFHToMuMu.root VBFHToMuMu_*
hadd -k -f DYJetsToLL.root DYJetsToLL_*
hadd -k -f ttTo2l2v.root ttTo2l2v_*
hadd -k -f ggH.root ggH_*
hadd -k -f ttH.root ttH_*
hadd -k -f ttTosemileptonic.root ttTosemileptonic_*
hadd -k -f WplusH.root WplusH_*
hadd -k -f WminusH.root WminusH_*
hadd -k -f WZTo1L1Nu2Q.root WZTo1L1Nu2Q_*
hadd -k -f WZTo3LNu.root WZTo3LNu_*
hadd -k -f WZTo2L2Q.root WZTo2L2Q_*
hadd -k -f WWTo2L2Nu.root WWTo2L2Nu_*
hadd -k -f WWToLNuQQ.root WWToLNuQQ_*
hadd -k -f WWW_4F.root WWW_4F_*
hadd -k -f WWZ_4F.root WWZ_4F_*
hadd -k -f Data2017.root Data2017_*
hadd -k -f ZH.root ZH_*
hadd -k -f ZZ.root ZZ_*
hadd -k -f ttJets_DiLept.root ttJets_DiLept_*
hadd -k -f TTZToLLNuNu.root TTZToLLNuNu_*
hadd -k -f TTWJetsToLNu.root TTWJetsToLNu_*